name: ip-analytics
services:

  zookeeper:
    image: bitnami/zookeeper:3.9.0
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "zookeeper", "2181", "|", "grep", "imok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ipnet

  kafka:
    image: bitnami/kafka:3.9.0
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server kafka:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ipnet

  fluent-bit:
    image: fluent/fluent-bit
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ${NGINX_LOG_DIR}:/var/log
      - ./conf:/fluent-bit/etc
    command: ["/fluent-bit/bin/fluent-bit", '-c', '/fluent-bit/etc/fluent-bit.conf']
    networks:
      - ipnet

  postgres:
    image: postgres:17.2
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - /opt/homebrew/var/postgresql@17:/var/lib/postgresql/data
    networks:
      - ipnet

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8978:8978"
    networks:
      - ipnet

  ipanalytics:
    build: .
    image: ip-analytics
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_started
    volumes:
      - .:/app
    command: "gunicorn --workers 2 --bind 0.0.0.0:3000 main:app -k gevent"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    ports:
      - "3000:3000"
    networks:
      - ipnet
    
  ipdashboard:
    build:
      context: ./dashboard/ip-dashboard
      dockerfile: Dockerfile
    image: ip-analytics-dash
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ipanalytics
    ports:
      - "8082:80"
    networks:
      - ipnet

networks:
  ipnet:
    driver: bridge

