services:

  fluent-bit:
    image: fluent/fluent-bit
    container_name: fluent-bit
    volumes:
      - .logs:/var/log
      - ./conf:/fluent-bit/etc
    ports:
      - "2020:2020"
    command: ["/fluent-bit/bin/fluent-bit", '-c', '/fluent-bit/etc/fluent-bit.conf']

  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  postgres:
    image: postgres:17.2
    container_name: postgres17
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRESS_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - ./scripts/init-db.sh:/docker-entry-point-initdb.d/init-db.sh
      - postgres-data:/var/lib/postgresql/data

    cloudbeaver:
      container_name: cloudbeaver
      image: dbeaver/cloudbeaver:latest
    ports:
      - "8978:8978"

    volumes:
      postgres-data:
